import './globals.css';
import { Inter } from 'next/font/google';
import { AuthContextProvider } from '@/contexts/AuthContext';
import { DarkModeProvider } from '@/contexts/DarkModeContext';
import Topbar from '@/components/MainLayout/Topbar';
import dynamic from 'next/dynamic';
const inter = Inter({ subsets: ['latin'] });

// Dynamically import EmbedHandler with ssr: false
const EmbedHandler = dynamic(() => import('@/contexts/EmbedHandler'), { ssr: false });

export const metadata = {
    title: 'Habit-Tracker',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} bg-background-light dark:bg-background-dark`}
            >
                <AuthContextProvider>
                    <DarkModeProvider>
                        <Topbar />
                        {children}
                        <EmbedHandler />
                    </DarkModeProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
}